<?php

/**
 * Returns page/post slug
 */
function the_slug()
{
	$current_page_id = get_the_ID();
	$current_page_slug = get_post_field('post_name', $current_page_id);
	return $current_page_slug;
}

/**
 * Returns part of string
 */
function excerpt($str, $length = 500, $trailing = '...')
{
	$str = strip_tags($str);
	$length -= mb_strlen($trailing);
	if(mb_strlen($str)> $length)
		return mb_substr($str, 0, $length).$trailing;
	else 
		return $str;
}

/**
 * Add menu
 */
add_theme_support( 'menus' );

if ( function_exists( 'register_nav_menus' ) ) {
	register_nav_menus(
		array(
			'header-menu' => 'Header Menu',
		)
	);
}

add_theme_support( 'post-thumbnails' );

//add_action( 'init', 'create_post_type' );
//function create_post_type() {
//	register_post_type( 'test',
//		array(
//			'labels' => array(
//				'name' => __( 'Test' ),
//				'singular_name' => __( 'Test' )
//			),
//		'public' => true,
//		'has_archive' => true,
//		'supports' => array( 'title', 'editor') 
//		)
//	);
//}

function cptui_register_my_cpts() {

	/**
	 * Post Type: Case Studies.
	 */

	$labels = [
		"name" => esc_html__( "Case Studies", "opascope" ),
		"singular_name" => esc_html__( "Case Study", "opascope" ),
		"menu_name" => esc_html__( "Case Studies", "opascope" ),
		"all_items" => esc_html__( "All Case Studies", "opascope" ),
		"add_new" => esc_html__( "Add new", "opascope" ),
		"add_new_item" => esc_html__( "Add new Case Study", "opascope" ),
		"edit_item" => esc_html__( "Edit Case Study", "opascope" ),
		"new_item" => esc_html__( "New Case Study", "opascope" ),
		"view_item" => esc_html__( "View Case Study", "opascope" ),
		"view_items" => esc_html__( "View Case Studies", "opascope" ),
		"search_items" => esc_html__( "Search Case Studies", "opascope" ),
		"not_found" => esc_html__( "No Case Studies found", "opascope" ),
		"not_found_in_trash" => esc_html__( "No Case Studies found in trash", "opascope" ),
		"parent" => esc_html__( "Parent Case Study:", "opascope" ),
		"featured_image" => esc_html__( "Featured image for this Case Study", "opascope" ),
		"set_featured_image" => esc_html__( "Set featured image for this Case Study", "opascope" ),
		"remove_featured_image" => esc_html__( "Remove featured image for this Case Study", "opascope" ),
		"use_featured_image" => esc_html__( "Use as featured image for this Case Study", "opascope" ),
		"archives" => esc_html__( "Case Study archives", "opascope" ),
		"insert_into_item" => esc_html__( "Insert into Case Study", "opascope" ),
		"uploaded_to_this_item" => esc_html__( "Upload to this Case Study", "opascope" ),
		"filter_items_list" => esc_html__( "Filter Case Studies list", "opascope" ),
		"items_list_navigation" => esc_html__( "Case Studies list navigation", "opascope" ),
		"items_list" => esc_html__( "Case Studies list", "opascope" ),
		"attributes" => esc_html__( "Case Studies attributes", "opascope" ),
		"name_admin_bar" => esc_html__( "Case Study", "opascope" ),
		"item_published" => esc_html__( "Case Study published", "opascope" ),
		"item_published_privately" => esc_html__( "Case Study published privately.", "opascope" ),
		"item_reverted_to_draft" => esc_html__( "Case Study reverted to draft.", "opascope" ),
		"item_scheduled" => esc_html__( "Case Study scheduled", "opascope" ),
		"item_updated" => esc_html__( "Case Study updated.", "opascope" ),
		"parent_item_colon" => esc_html__( "Parent Case Study:", "opascope" ),
	];

	$args = [
		"label" => esc_html__( "Case Studies", "opascope" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"rest_namespace" => "wp/v2",
		"has_archive" => false,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"can_export" => false,
		"rewrite" => [ "slug" => "case-study", "with_front" => true ],
		"query_var" => true,
		"menu_icon" => "dashicons-edit-page",
		"supports" => [ "title", "editor", "thumbnail", "custom-fields" ],
		"taxonomies" => [ "category", "post_tag" ],
		"show_in_graphql" => false,
	];

	register_post_type( "case-study", $args );

	/**
	 * Post Type: Jobs.
	 */

	$labels = [
		"name" => esc_html__( "Jobs", "opascope" ),
		"singular_name" => esc_html__( "Job", "opascope" ),
		"menu_name" => esc_html__( "Jobs", "opascope" ),
		"all_items" => esc_html__( "All Jobs", "opascope" ),
		"add_new" => esc_html__( "Add new", "opascope" ),
		"add_new_item" => esc_html__( "Add new Job", "opascope" ),
		"edit_item" => esc_html__( "Edit Job", "opascope" ),
		"new_item" => esc_html__( "New Job", "opascope" ),
		"view_item" => esc_html__( "View Job", "opascope" ),
		"view_items" => esc_html__( "View Jobs", "opascope" ),
		"search_items" => esc_html__( "Search Jobs", "opascope" ),
		"not_found" => esc_html__( "No Jobs found", "opascope" ),
		"not_found_in_trash" => esc_html__( "No Jobs found in trash", "opascope" ),
		"parent" => esc_html__( "Parent Job:", "opascope" ),
		"featured_image" => esc_html__( "Featured image for this Job", "opascope" ),
		"set_featured_image" => esc_html__( "Set featured image for this Job", "opascope" ),
		"remove_featured_image" => esc_html__( "Remove featured image for this Job", "opascope" ),
		"use_featured_image" => esc_html__( "Use as featured image for this Job", "opascope" ),
		"archives" => esc_html__( "Job archives", "opascope" ),
		"insert_into_item" => esc_html__( "Insert into Job", "opascope" ),
		"uploaded_to_this_item" => esc_html__( "Upload to this Job", "opascope" ),
		"filter_items_list" => esc_html__( "Filter Jobs list", "opascope" ),
		"items_list_navigation" => esc_html__( "Jobs list navigation", "opascope" ),
		"items_list" => esc_html__( "Jobs list", "opascope" ),
		"attributes" => esc_html__( "Jobs attributes", "opascope" ),
		"name_admin_bar" => esc_html__( "Job", "opascope" ),
		"item_published" => esc_html__( "Job published", "opascope" ),
		"item_published_privately" => esc_html__( "Job published privately.", "opascope" ),
		"item_reverted_to_draft" => esc_html__( "Job reverted to draft.", "opascope" ),
		"item_scheduled" => esc_html__( "Job scheduled", "opascope" ),
		"item_updated" => esc_html__( "Job updated.", "opascope" ),
		"parent_item_colon" => esc_html__( "Parent Job:", "opascope" ),
	];

	$args = [
		"label" => esc_html__( "Jobs", "opascope" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"rest_namespace" => "wp/v2",
		"has_archive" => false,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"can_export" => true,
		"rewrite" => [ "slug" => "job", "with_front" => true ],
		"query_var" => true,
		"menu_icon" => "https://opascope.com/wp-content/uploads/2023/05/232190-1.png",
		"supports" => [ "title", "editor", "thumbnail", "custom-fields" ],
		"taxonomies" => [ "job_category" ],
		"show_in_graphql" => false,
	];

	register_post_type( "job", $args );

	/**
	 * Post Type: insights.
	 */

	$labels = [
		"name" => esc_html__( "insights", "opascope" ),
		"singular_name" => esc_html__( "insights", "opascope" ),
		"menu_name" => esc_html__( "My insights", "opascope" ),
		"all_items" => esc_html__( "All insights", "opascope" ),
		"add_new" => esc_html__( "Add new", "opascope" ),
		"add_new_item" => esc_html__( "Add new insight", "opascope" ),
		"edit_item" => esc_html__( "Edit insight", "opascope" ),
		"new_item" => esc_html__( "New insight", "opascope" ),
		"view_item" => esc_html__( "View insight", "opascope" ),
		"view_items" => esc_html__( "View insights", "opascope" ),
		"search_items" => esc_html__( "Search insights", "opascope" ),
		"not_found" => esc_html__( "No insights found", "opascope" ),
		"not_found_in_trash" => esc_html__( "No insights found in trash", "opascope" ),
		"parent" => esc_html__( "Parent insight:", "opascope" ),
		"featured_image" => esc_html__( "Featured image for this insight", "opascope" ),
		"set_featured_image" => esc_html__( "Set featured image for this insight", "opascope" ),
		"remove_featured_image" => esc_html__( "Remove featured image for this insight", "opascope" ),
		"use_featured_image" => esc_html__( "Use as featured image for this insight", "opascope" ),
		"archives" => esc_html__( "insight archives", "opascope" ),
		"insert_into_item" => esc_html__( "Insert into insight", "opascope" ),
		"uploaded_to_this_item" => esc_html__( "Upload to this insight", "opascope" ),
		"filter_items_list" => esc_html__( "Filter insights list", "opascope" ),
		"items_list_navigation" => esc_html__( "insights list navigation", "opascope" ),
		"items_list" => esc_html__( "insights list", "opascope" ),
		"attributes" => esc_html__( "insights attributes", "opascope" ),
		"name_admin_bar" => esc_html__( "insight", "opascope" ),
		"item_published" => esc_html__( "insight published", "opascope" ),
		"item_published_privately" => esc_html__( "insight published privately.", "opascope" ),
		"item_reverted_to_draft" => esc_html__( "insight reverted to draft.", "opascope" ),
		"item_scheduled" => esc_html__( "insight scheduled", "opascope" ),
		"item_updated" => esc_html__( "insight updated.", "opascope" ),
		"parent_item_colon" => esc_html__( "Parent insight:", "opascope" ),
	];

	$args = [
		"label" => esc_html__( "insights", "opascope" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"rest_namespace" => "wp/v2",
		"has_archive" => "insights",
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"can_export" => false,
		"rewrite" => [ "slug" => "insight", "with_front" => false ],
		"query_var" => true,
		"menu_icon" => "dashicons-welcome-widgets-menus",
		"supports" => [ "title", "editor", "thumbnail", "custom-fields" ],
		"show_in_graphql" => false,
	];

	register_post_type( "insight", $args );
}

add_action( 'init', 'cptui_register_my_cpts' );

function cptui_register_my_taxes() {

	/**
	 * Taxonomy: Categories.
	 */

	$labels = [
		"name" => esc_html__( "Categories", "astra-child" ),
		"singular_name" => esc_html__( "Category", "astra-child" ),
		"menu_name" => esc_html__( "Categories", "astra-child" ),
		"all_items" => esc_html__( "All Categories", "astra-child" ),
		"edit_item" => esc_html__( "Edit Category", "astra-child" ),
		"view_item" => esc_html__( "View Category", "astra-child" ),
		"update_item" => esc_html__( "Update Category name", "astra-child" ),
		"add_new_item" => esc_html__( "Add new Category", "astra-child" ),
		"new_item_name" => esc_html__( "New Category name", "astra-child" ),
		"parent_item" => esc_html__( "Parent Category", "astra-child" ),
		"parent_item_colon" => esc_html__( "Parent Category:", "astra-child" ),
		"search_items" => esc_html__( "Search Categories", "astra-child" ),
		"popular_items" => esc_html__( "Popular Categories", "astra-child" ),
		"separate_items_with_commas" => esc_html__( "Separate Categories with commas", "astra-child" ),
		"add_or_remove_items" => esc_html__( "Add or remove Categories", "astra-child" ),
		"choose_from_most_used" => esc_html__( "Choose from the most used Categories", "astra-child" ),
		"not_found" => esc_html__( "No Categories found", "astra-child" ),
		"no_terms" => esc_html__( "No Categories", "astra-child" ),
		"items_list_navigation" => esc_html__( "Categories list navigation", "astra-child" ),
		"items_list" => esc_html__( "Categories list", "astra-child" ),
		"back_to_items" => esc_html__( "Back to Categories", "astra-child" ),
		"name_field_description" => esc_html__( "The name is how it appears on your site.", "astra-child" ),
		"parent_field_description" => esc_html__( "Assign a parent term to create a hierarchy. The term Jazz, for example, would be the parent of Bebop and Big Band.", "astra-child" ),
		"slug_field_description" => esc_html__( "The slug is the URL-friendly version of the name. It is usually all lowercase and contains only letters, numbers, and hyphens.", "astra-child" ),
		"desc_field_description" => esc_html__( "The description is not prominent by default; however, some themes may show it.", "astra-child" ),
	];

	
	$args = [
		"label" => esc_html__( "Categories", "astra-child" ),
		"labels" => $labels,
		"public" => true,
		"publicly_queryable" => true,
		"hierarchical" => true,
		"show_ui" => true,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"query_var" => true,
		"rewrite" => [ 'slug' => 'job_category', 'with_front' => true, ],
		"show_admin_column" => true,
		"show_in_rest" => true,
		"show_tagcloud" => false,
		"rest_base" => "job_category",
		"rest_controller_class" => "WP_REST_Terms_Controller",
		"rest_namespace" => "wp/v2",
		"show_in_quick_edit" => true,
		"sort" => true,
		"show_in_graphql" => false,
	];
	register_taxonomy( "job_category", [ "job" ], $args );

	/**
	 * Taxonomy: Tags.
	 */

	$labels = [
		"name" => esc_html__( "Tags", "astra-child" ),
		"singular_name" => esc_html__( "Tag", "astra-child" ),
		"menu_name" => esc_html__( "Tags", "astra-child" ),
		"all_items" => esc_html__( "All Tags", "astra-child" ),
		"edit_item" => esc_html__( "Edit Tag", "astra-child" ),
		"view_item" => esc_html__( "View Tag", "astra-child" ),
		"update_item" => esc_html__( "Update Tag name", "astra-child" ),
		"add_new_item" => esc_html__( "Add new Tag", "astra-child" ),
		"new_item_name" => esc_html__( "New Tag name", "astra-child" ),
		"parent_item" => esc_html__( "Parent Tag", "astra-child" ),
		"parent_item_colon" => esc_html__( "Parent Tag:", "astra-child" ),
		"search_items" => esc_html__( "Search Tags", "astra-child" ),
		"popular_items" => esc_html__( "Popular Tags", "astra-child" ),
		"separate_items_with_commas" => esc_html__( "Separate Tags with commas", "astra-child" ),
		"add_or_remove_items" => esc_html__( "Add or remove Tags", "astra-child" ),
		"choose_from_most_used" => esc_html__( "Choose from the most used Tags", "astra-child" ),
		"not_found" => esc_html__( "No Tags found", "astra-child" ),
		"no_terms" => esc_html__( "No Tags", "astra-child" ),
		"items_list_navigation" => esc_html__( "Tags list navigation", "astra-child" ),
		"items_list" => esc_html__( "Tags list", "astra-child" ),
		"back_to_items" => esc_html__( "Back to Tags", "astra-child" ),
		"name_field_description" => esc_html__( "The name is how it appears on your site.", "astra-child" ),
		"parent_field_description" => esc_html__( "Assign a parent term to create a hierarchy. The term Jazz, for example, would be the parent of Bebop and Big Band.", "astra-child" ),
		"slug_field_description" => esc_html__( "The slug is the URL-friendly version of the name. It is usually all lowercase and contains only letters, numbers, and hyphens.", "astra-child" ),
		"desc_field_description" => esc_html__( "The description is not prominent by default; however, some themes may show it.", "astra-child" ),
	];

	
	$args = [
		"label" => esc_html__( "Tags", "astra-child" ),
		"labels" => $labels,
		"public" => true,
		"publicly_queryable" => true,
		"hierarchical" => true,
		"show_ui" => true,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"query_var" => true,
		"rewrite" => [ 'slug' => 'insight-category', 'with_front' => true, ],
		"show_admin_column" => true,
		"show_in_rest" => true,
		"show_tagcloud" => false,
		"rest_base" => "insight-category",
		"rest_controller_class" => "WP_REST_Terms_Controller",
		"rest_namespace" => "wp/v2",
		"show_in_quick_edit" => true,
		"sort" => true,
		"show_in_graphql" => false,
	];
	register_taxonomy( "insight-category", [ "insight" ], $args );

	/**
	 * Taxonomy: Categories.
	 */

	$labels = [
		"name" => esc_html__( "Categories", "astra-child" ),
		"singular_name" => esc_html__( "Category", "astra-child" ),
		"menu_name" => esc_html__( "Categories", "astra-child" ),
		"all_items" => esc_html__( "All Categories", "astra-child" ),
		"edit_item" => esc_html__( "Edit Category", "astra-child" ),
		"view_item" => esc_html__( "View Category", "astra-child" ),
		"update_item" => esc_html__( "Update Category name", "astra-child" ),
		"add_new_item" => esc_html__( "Add new Category", "astra-child" ),
		"new_item_name" => esc_html__( "New Category name", "astra-child" ),
		"parent_item" => esc_html__( "Parent Category", "astra-child" ),
		"parent_item_colon" => esc_html__( "Parent Category:", "astra-child" ),
		"search_items" => esc_html__( "Search Categories", "astra-child" ),
		"popular_items" => esc_html__( "Popular Categories", "astra-child" ),
		"separate_items_with_commas" => esc_html__( "Separate Categories with commas", "astra-child" ),
		"add_or_remove_items" => esc_html__( "Add or remove Categories", "astra-child" ),
		"choose_from_most_used" => esc_html__( "Choose from the most used Categories", "astra-child" ),
		"not_found" => esc_html__( "No Categories found", "astra-child" ),
		"no_terms" => esc_html__( "No Categories", "astra-child" ),
		"items_list_navigation" => esc_html__( "Categories list navigation", "astra-child" ),
		"items_list" => esc_html__( "Categories list", "astra-child" ),
		"back_to_items" => esc_html__( "Back to Categories", "astra-child" ),
		"name_field_description" => esc_html__( "The name is how it appears on your site.", "astra-child" ),
		"parent_field_description" => esc_html__( "Assign a parent term to create a hierarchy. The term Jazz, for example, would be the parent of Bebop and Big Band.", "astra-child" ),
		"slug_field_description" => esc_html__( "The slug is the URL-friendly version of the name. It is usually all lowercase and contains only letters, numbers, and hyphens.", "astra-child" ),
		"desc_field_description" => esc_html__( "The description is not prominent by default; however, some themes may show it.", "astra-child" ),
	];

	
	$args = [
		"label" => esc_html__( "Categories", "astra-child" ),
		"labels" => $labels,
		"public" => true,
		"publicly_queryable" => true,
		"hierarchical" => false,
		"show_ui" => true,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"query_var" => true,
		"rewrite" => [ 'slug' => 'insights-category', 'with_front' => true, ],
		"show_admin_column" => false,
		"show_in_rest" => true,
		"show_tagcloud" => false,
		"rest_base" => "insights-category",
		"rest_controller_class" => "WP_REST_Terms_Controller",
		"rest_namespace" => "wp/v2",
		"show_in_quick_edit" => false,
		"sort" => false,
		"show_in_graphql" => false,
	];
	register_taxonomy( "insights-category", [ "insight" ], $args );
}
add_action( 'init', 'cptui_register_my_taxes' );

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_62e179b724abc',
	'title' => 'Careers Page',
	'fields' => array(
		array(
			'key' => 'field_62e179c34675a',
			'label' => 'Short Description (Right)',
			'name' => 'content',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_645bcb4d19670',
			'label' => 'Sub Section',
			'name' => 'sub_section',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_645bcb111966f',
					'label' => 'Sub Heading',
					'name' => 'sub_heading',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bcb6e19671',
					'label' => 'Body Text',
					'name' => 'body_text',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_645bc7598b854',
			'label' => 'Values section',
			'name' => 'values_section',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_645bc7598b855',
					'label' => 'Main Heading',
					'name' => 'main_heading',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bc7598b856',
					'label' => 'Heading (value 1)',
					'name' => 'heading_value_1',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bc7598b857',
					'label' => 'Heading (value 2)',
					'name' => 'heading_value_2',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bc7598b858',
					'label' => 'Heading (value 3)',
					'name' => 'heading_value_3',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bc7598b859',
					'label' => 'Description (value 1)',
					'name' => 'description_value_1',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bc7598b85a',
					'label' => 'Description (value 2)',
					'name' => 'description_value_2',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bc7598b85b',
					'label' => 'Description (value3)',
					'name' => 'description_value_3',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bc7598b85c',
					'label' => 'Heading (value 4)',
					'name' => 'heading_value_4',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bc7598b85d',
					'label' => 'Heading (value 5)',
					'name' => 'heading_value_5',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bc7598b85e',
					'label' => 'Heading (value 6)',
					'name' => 'heading_value_6',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bc7598b85f',
					'label' => 'Description (value 4)',
					'name' => 'description_value_4',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bc7598b860',
					'label' => 'Description (value 5)',
					'name' => 'description_value_5',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_645bc7598b861',
					'label' => 'Description (value 6)',
					'name' => 'description_value_6',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_62e273fc70d24',
			'label' => 'Benefits section',
			'name' => 'benefits_section',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_62e274cae64e5',
					'label' => 'Main Heading',
					'name' => 'main_heading',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e2740970d25',
					'label' => 'Heading (benefit 1)',
					'name' => 'heading_benefit_1',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e2743870d26',
					'label' => 'Heading (benefit 2)',
					'name' => 'heading_benefit_2',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e2743970d27',
					'label' => 'Heading (benefit 3)',
					'name' => 'heading_benefit_3',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e2744170d2b',
					'label' => 'Description (benefit 1)',
					'name' => 'description_benefit_1',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e2745370d2c',
					'label' => 'Description (benefit 2)',
					'name' => 'description_benefit_2',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e2745370d2d',
					'label' => 'Description (benefit 3)',
					'name' => 'description_benefit_3',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e2743b70d28',
					'label' => 'Heading (benefit 4)',
					'name' => 'heading_benefit_4',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e2743c70d29',
					'label' => 'Heading (benefit 5)',
					'name' => 'heading_benefit_5',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e2743d70d2a',
					'label' => 'Heading (benefit 6)',
					'name' => 'heading_benefit_6',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e2745570d2e',
					'label' => 'Description (benefit 4)',
					'name' => 'description_benefit_4',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e2745670d2f',
					'label' => 'Description (benefit 5)',
					'name' => 'description_benefit_5',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e2745770d30',
					'label' => 'Description (benefit 6)',
					'name' => 'description_benefit_6',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '911',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_61e84c31e7bdd',
	'title' => 'Case Studies Fields',
	'fields' => array(
		array(
			'key' => 'field_61e84c5130dc0',
			'label' => 'Content',
			'name' => 'content',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_61e84c6230dc1',
			'label' => 'PDF link text',
			'name' => 'pdf_link_text',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => 'acf-hidden',
				'id' => '',
			),
			'default_value' => 'Read Now',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_61e84caa30dc2',
			'label' => 'PDF link',
			'name' => 'pdf_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => 'acf-hidden',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_6203df74b24a4',
			'label' => 'dFlip ID',
			'name' => 'dflip_id',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_6478cd37ed74c',
			'label' => 'Summary',
			'name' => 'summary',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6478ccb5ed74b',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Summary',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478cd70ed74d',
					'label' => 'Description',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '67',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_6478cf379a0e4',
			'label' => 'The Problem',
			'name' => 'the_problem',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6478cf379a0e5',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'The Problem',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478cf379a0e6',
					'label' => 'Description',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '67',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_647a06361ecf3',
			'label' => 'The Solution',
			'name' => 'the_solution',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_647a06361ecf4',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'The Solution',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_647a06361ecf5',
					'label' => 'Description',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '67',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_647a067ceb569',
			'label' => 'The Results',
			'name' => 'the_results',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_647a067deb56a',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'The Results',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_647a067deb56b',
					'label' => 'Description',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '67',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_647a08ddf8325',
			'label' => 'Statistics',
			'name' => 'statistics',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_647a08ebf8326',
					'label' => 'Title (First Stat)',
					'name' => 'title_first_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_647a155df832a',
					'label' => 'Content (First Stat)',
					'name' => 'content_first_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64c2ae6d07fb9',
					'label' => 'Image (First Stat)',
					'name' => 'image_first_stat',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'thumbnail',
				),
				array(
					'key' => 'field_647a097cf8327',
					'label' => 'Title (Second Stat)',
					'name' => 'title_second_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_647a156df832b',
					'label' => 'Content (Second Stat)',
					'name' => 'content_second_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64c2aea607fba',
					'label' => 'Image (Second Stat)',
					'name' => 'image_second_stat',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'thumbnail',
				),
				array(
					'key' => 'field_647a0996f8328',
					'label' => 'Title (Third Stat)',
					'name' => 'title_third_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_647a17a5f832c',
					'label' => 'Content (Third Stat)',
					'name' => 'content_third_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64c2aebb07fbb',
					'label' => 'Image (Third Stat)',
					'name' => 'image_third_stat',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'thumbnail',
				),
			),
		),
		array(
			'key' => 'field_647a189fa6b8f',
			'label' => 'Quote Section',
			'name' => 'quote_section',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_647a18dba6b90',
					'label' => 'Quote',
					'name' => 'quote',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_647a1942a6b91',
					'label' => 'Author',
					'name' => 'author',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_64f0b9592855d',
			'label' => 'Block Section',
			'name' => 'block_section',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_64f0b9592855e',
					'label' => 'Block Title',
					'name' => 'block_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64f0b9592855f',
					'label' => 'Block Text',
					'name' => 'block_text',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'case-study',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_61e85aba97dc6',
	'title' => 'Case Study Page',
	'fields' => array(
		array(
			'key' => 'field_61e85ac7698b3',
			'label' => 'Content 1',
			'name' => 'content_1',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_6478bdcd02869',
			'label' => 'Content 2',
			'name' => 'content_2',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_6478bdcf0286a',
			'label' => 'Content 3',
			'name' => 'content_3',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'archive-case-study.php',
			),
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '364',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_64538de3d3f5d',
	'title' => 'Insight Fields',
	'fields' => array(
		array(
			'key' => 'field_65045e6f5b4d9',
			'label' => 'Featured Icon',
			'name' => 'featured_icon',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_64538de72e98e',
			'label' => 'Excerpt',
			'name' => 'excerpt',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64d3b4d286f42',
			'label' => 'Statistics',
			'name' => 'statistics',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_64d3b4da86f43',
					'label' => 'Title (First Stat)',
					'name' => 'title_first_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64d3b4f086f44',
					'label' => 'Content (First Stat)',
					'name' => 'content_first_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64d3b56a86f45',
					'label' => 'Title (Second Stat)',
					'name' => 'title_second_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64d3b5bd86f46',
					'label' => 'Content (Second Stat)',
					'name' => 'content_second_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64d3b5d186f47',
					'label' => 'Title (Third Stat)',
					'name' => 'title_third_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64d3b6fb86f48',
					'label' => 'Content (Third Stat)',
					'name' => 'content_third_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64d3b71886f49',
					'label' => 'Title (Fourth Stat)',
					'name' => 'title_fourth_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64d3b75186f4a',
					'label' => 'Content (Fourth Stat)',
					'name' => 'content_fourth_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'insight',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_62e17d5c3a2dc',
	'title' => 'Job Fields',
	'fields' => array(
		array(
			'key' => 'field_62e17d6767136',
			'label' => 'Apply Link',
			'name' => 'apply_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'job',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );


